---
- name: Update /etc/sysconfig/docker-storage-setup configuration to use a persistent path from AWS
  hosts: all
  tasks:
  - name: Determine disk used for PV in docker-vg volume group
    shell: vgdisplay docker-vg -v | grep "PV Name" -A1 | awk '{print $3}' | sed -n '1p' | sed 's/.\{2\}$//'
    register: UUID

  - debug: msg={{ UUID.stdout }}

  - name: Grab NVME Path from udevinfo info {{ UUID.stdout }}
    shell: udevadm info {{ UUID.stdout }} | sed -n '3p' | sed 's/^.\{,14\}//'
    register: NVME_PATH

  - debug: msg={{ NVME_PATH.stdout }}

  - name: Backup /etc/sysconfig/docker-storage-setup to /etc/sysconfig/docker-storage-setup.{{ ansible_date_time.date }}.{{ ansible_date_time.time }}
    copy:
      src: /etc/sysconfig/docker-storage-setup
      dest: /etc/sysconfig/docker-storage-setup.{{ ansible_date_time.date }}.{{ ansible_date_time.time }}
      remote_src: yes

  - name: Update /etc/sysconfig/docker-storage-setup with Persistent Device Patch
    lineinfile:
      path: /etc/sysconfig/docker-storage-setup
      regexp: '^DEVS'
      line: 'DEVS=/dev/disk/by-id/{{ NVME_PATH.stdout }}'

  - name: Remove Incorrrect Disk from Volume Group
    shell: vgreduce --removemissing docker-vg

  - name: Activate Volume Group
    shell: lvchange -a y docker-vg
