#!/bin/bash

CONF_FILE=/etc/etcd/${NEW_ETCD}.added
ETCD_CONF=/etc/etcd/etcd.conf

ETCD_NAME=$(cat $CONF_FILE | grep "ETCD_NAME=" | cut -d '"' -f 2)
ETCD_INITIAL_CLUSTER=$(cat $CONF_FILE | grep "ETCD_INITIAL_CLUSTER=" | cut -d '"' -f 2)
ETCD_INITIAL_CLUSTER_STATE=$(cat $CONF_FILE | grep "ETCD_INITIAL_CLUSTER_STATE=" | cut -d '"' -f 2)

LINE_ETCD_NAME="ETCD_NAME=${ETCD_NAME}"
LINE_ETCD_INITIAL_CLUSTER="ETCD_INITIAL_CLUSTER=${ETCD_INITIAL_CLUSTER}"
LINE_ETCD_INITIAL_CLUSTER_STATE="ETCD_INITIAL_CLUSTER_STATE=${ETCD_INITIAL_CLUSTER_STATE}"
LINE_ETCD_LISTEN_PEER_URLS="ETCD_LISTEN_PEER_URLS=https://${NEW_ETCD_IP}:2380"
LINE_ETCD_LISTEN_CLIENT_URLS="ETCD_LISTEN_CLIENT_URLS=https://${NEW_ETCD_IP}:2379"
LINE_ETCD_INITIAL_ADVERTISE_PEER_URLS="ETCD_INITIAL_ADVERTISE_PEER_URLS=https://${NEW_ETCD_IP}:2380"
LINE_ETCD_ADVERTISE_CLIENT_URLS="ETCD_ADVERTISE_CLIENT_URLS=https://${NEW_ETCD_IP}:2379"

sed -i '/^ETCD_NAME=/c\'"${LINE_ETCD_NAME}"'' $ETCD_CONF
sed -i '/^ETCD_INITIAL_CLUSTER=/c\'"${LINE_ETCD_INITIAL_CLUSTER}"'' $ETCD_CONF
sed -i '/^ETCD_INITIAL_CLUSTER_STATE=/c\'"${LINE_ETCD_INITIAL_CLUSTER_STATE}"'' $ETCD_CONF
sed -i '/^ETCD_LISTEN_PEER_URLS=/c\'"${LINE_ETCD_LISTEN_PEER_URLS}"'' $ETCD_CONF
sed -i '/^ETCD_LISTEN_CLIENT_URLS=/c\'"${LINE_ETCD_LISTEN_CLIENT_URLS}"'' $ETCD_CONF
sed -i '/^ETCD_INITIAL_ADVERTISE_PEER_URLS=/c\'"${LINE_ETCD_INITIAL_ADVERTISE_PEER_URLS}"'' $ETCD_CONF
sed -i '/^ETCD_ADVERTISE_CLIENT_URLS=/c\'"${LINE_ETCD_ADVERTISE_CLIENT_URLS}"'' $ETCD_CONF
