{
 "title": "K8s / USE Method / Node",
 "time": { "from": "2020-07-20T19:21:17.674Z", "to": "2020-07-20T19:38:05.118Z" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "node",
    "label": "node",
    "query": "label_values(kube_node_info, node)"
   }
  ]
 },
 "panels": [
  {
   "title": "node_procs_running",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_procs_running{job=\"node-exporter\"} \r\n        * on (namespace, pod) group_left(node)\r\n          node_namespace_pod:kube_pod_info:{node=\"$node\"}",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "CPU Utilisation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node:node_cpu_utilisation:avg1m{node=\"$node\"}",
     "legendFormat": "Utilisation"
    }
   ]
  },
  {
   "title": "CPU Saturation (Load1)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node:node_cpu_saturation_load1:{node=\"$node\"}",
     "legendFormat": "Saturation"
    }
   ]
  },
  {
   "title": "cpu modes rate 1m",
   "type": "graph",
   "description": "per-second rate over past 1 minute of cpu time spent in each mode",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (node,mode) ( irate(node_cpu{job=\"node-exporter\"}[1m]) * on (namespace, pod) group_left(node)\r\n          node_namespace_pod:kube_pod_info:{ node = \"$node\" })  / on(node) group_left node:node_num_cpu:sum )",
     "legendFormat": "{{ mode }}"
    }
   ]
  },
  {
   "title": "container cpu usage of node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pod_name:container_cpu_usage:sum * ignoring (node) group_left(node) max by (node, namespace, pod_name) ( label_replace(kube_pod_info{job=\"kube-state-metrics\",service=\"kube-state-metrics\", node= \"$node\"}, \"pod_name\", \"$1\", \"pod\", \"(.*)\")  )",
     "legendFormat": "{{namespace}} {{pod_name}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Memory Utilisation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node:node_memory_utilisation:{node=\"$node\"}",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Memory Saturation (Swap I/O)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "node:node_memory_swap_io_bytes:sum_rate{node=\"$node\"}",
     "legendFormat": "Swap IO"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Disk IO Utilisation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node:node_disk_utilisation:avg_irate{node=\"$node\"}",
     "legendFormat": "Utilisation"
    }
   ]
  },
  {
   "title": "Disk IO Saturation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node:node_disk_saturation:avg_irate{node=\"$node\"}",
     "legendFormat": "Saturation"
    }
   ]
  },
  { "title": "Net", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Net Utilisation (Transmitted)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "node:node_net_utilisation:sum_irate{node=\"$node\"}",
     "legendFormat": "Utilisation"
    }
   ]
  },
  {
   "title": "Net Saturation (Dropped)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "node:node_net_saturation:sum_irate{node=\"$node\"}",
     "legendFormat": "Saturation"
    }
   ]
  },
  {
   "title": "sockstat",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_sockstat_TCP_alloc{job=\"node-exporter\"} * on (namespace, pod) group_left(node)\r\n          node_namespace_pod:kube_pod_info:{ node = \"$node\" }",
     "legendFormat": "TCP alloc"
    },
    {
     "expr": "node_sockstat_TCP_inuse{job=\"node-exporter\"} * on (namespace, pod) group_left(node)\r\n          node_namespace_pod:kube_pod_info:{ node = \"$node\" }",
     "legendFormat": "TCP inuse"
    },
    {
     "expr": "node_sockstat_TCP_tw{job=\"node-exporter\"} * on (namespace, pod) group_left(node)\r\n          node_namespace_pod:kube_pod_info:{ node = \"$node\" }",
     "legendFormat": "TCP tw"
    },
    {
     "expr": "node_sockstat_TCP_orphan{job=\"node-exporter\"} * on (namespace, pod) group_left(node)\r\n          node_namespace_pod:kube_pod_info:{ node = \"$node\" }",
     "legendFormat": "TCP orphan"
    },
    {
     "expr": "node_sockstat_UDP_mem{job=\"node-exporter\"} * on (namespace, pod) group_left(node)\r\n          node_namespace_pod:kube_pod_info:{ node = \"$node\" }",
     "legendFormat": "UDP mem"
    },
    {
     "expr": "node_sockstat_UDP_inuse{job=\"node-exporter\"} * on (namespace, pod) group_left(node)\r\n          node_namespace_pod:kube_pod_info:{ node = \"$node\" }",
     "legendFormat": "UDP inuse"
    },
    {
     "expr": "node_sockstat_RAW_inuse{job=\"node-exporter\"} * on (namespace, pod) group_left(node)\r\n          node_namespace_pod:kube_pod_info:{ node = \"$node\" }",
     "legendFormat": "RAW inuse"
    },
    {
     "expr": "node_sockstat_UDPLITE_inuse{job=\"node-exporter\"} * on (namespace, pod) group_left(node)\r\n          node_namespace_pod:kube_pod_info:{ node = \"$node\" }",
     "legendFormat": "UDPLITE inuse"
    }
   ]
  },
  {
   "title": "sockstat_mem_bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_sockstat_TCP_mem_bytes{job=\"node-exporter\"} * on (namespace, pod) group_left(node)\r\n          node_namespace_pod:kube_pod_info:{ node = \"$node\" }",
     "legendFormat": "TCP mem bytes"
    },
    {
     "expr": "node_sockstat_UDP_mem_bytes{job=\"node-exporter\"} * on (namespace, pod) group_left(node)\r\n          node_namespace_pod:kube_pod_info:{ node = \"$node\" }",
     "legendFormat": "UDP"
    },
    {
     "expr": "node_sockstat_FRAG_memory{job=\"node-exporter\"} * on (namespace, pod) group_left(node)\r\n          node_namespace_pod:kube_pod_info:{ node = \"$node\" }",
     "legendFormat": "FRAG"
    },
    {
     "expr": "node_sockstat_TCP_mem{job=\"node-exporter\"} * on (namespace, pod) group_left(node)\r\n          node_namespace_pod:kube_pod_info:{ node = \"$node\" }",
     "legendFormat": "TCP mem"
    }
   ]
  },
  {
   "title": "netstat TCP Current Established",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 98 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{job=\"node-exporter\"} * on (namespace, pod) group_left(node)\r\n          node_namespace_pod:kube_pod_info:{ node = \"$node\" }",
     "legendFormat": "TCP"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 106 } },
  {
   "title": "Disk Utilisation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 107 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node:node_filesystem_usage:\n* on (namespace, pod) group_left (node) node_namespace_pod:kube_pod_info:{node=\"$node\"}\n",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "node_scrape_collector_duration_seconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 114 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_scrape_collector_duration_seconds{job=\"node-exporter\"} * on (namespace, pod) group_left(node)\r\n          node_namespace_pod:kube_pod_info:{ node = \"$node\" }",
     "legendFormat": "{{collector}}"
    }
   ]
  }
 ]
}