{
 "title": "etcd",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "etcd disk wal fsync", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "m0 etcd disk wal fsync duration seconds",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "etcd_disk_wal_fsync_duration_seconds_bucket{job=\"etcd\",pod=~\".*etcd.*0.*\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "m1 etcd disk wal fsync duration seconds",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "etcd_disk_wal_fsync_duration_seconds_bucket{job=\"etcd\",pod=~\".*etcd.*1.*\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "m2 etcd disk wal fsync duration seconds",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "etcd_disk_wal_fsync_duration_seconds_bucket{job=\"etcd\",pod=~\".*etcd.*2.*\"}",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}