{
 "title": "Cluster Status / Pods",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Projects",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "count(kube_namespace_created)", "legendFormat": "Projects" }
   ]
  },
  {
   "title": "Total Pods",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=~\".*\"})",
     "legendFormat": "Pods"
    }
   ]
  },
  {
   "title": "Running Pods",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Running\"})",
     "legendFormat": "Pods"
    }
   ]
  },
  {
   "title": "Failed Pods",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase!~\"Running|Succeeded|\"})",
     "legendFormat": "Pods"
    }
   ]
  },
  {
   "title": "Changes in the cluster",
   "type": "graph",
   "description": "Pod deployment",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(changes(kubelet_running_container_count[10m]))",
     "legendFormat": "Pod deploy"
    },
    {
     "expr": "sum(changes(kube_pod_status_phase{phase!~\"Running|Succeeded|\"}[10m]))",
     "legendFormat": "Failed Pod"
    }
   ]
  }
 ]
}