{
 "title": "apiserver-wide",
 "time": { "from": "2020-07-23T16:50:00.000Z", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "api inflight requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "api requests inflight",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "apiserver_current_inflight_requests",
     "legendFormat": "{{requestKind}}@{{instance}}"
    }
   ]
  },
  {
   "title": "request latencies 99pct",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "apiserver_request_latencies_summary{verb!=\"WATCH\",subresource=\"\",resource=\"pods\",quantile=\"0.99\"}",
     "legendFormat": "{{verb}} {{resource}}@{{instance}}"
    }
   ]
  },
  {
   "title": "request latencies 90pct",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "apiserver_request_latencies_summary{verb!=\"WATCH\",subresource=\"\",resource=\"pods\",quantile=\"0.9\"}",
     "legendFormat": "{{verb}} {{resource}}@{{instance}}"
    }
   ]
  },
  {
   "title": "request latencies 0.5pct",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "apiserver_request_latencies_summary{verb!=\"WATCH\",subresource=\"\",resource=\"pods\",quantile=\"0.5\"}",
     "legendFormat": "{{verb}} {{resource}}@{{instance}}"
    }
   ]
  },
  { "title": "job and endpoint", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "job workqueue",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 26 },
   "repeat": "controller",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "job_adds", "legendFormat": "adds  {{pod}}" },
    { "expr": "job_retries", "legendFormat": "retries  {{pod}}" },
    { "expr": "job_depth", "legendFormat": "depth  {{pod}}" }
   ]
  },
  {
   "title": "job work duration",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 26 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    { "expr": "job_work_duration", "legendFormat": " {{quantile}} {{pod}}" }
   ]
  },
  {
   "title": "job queue latency",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 26 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    { "expr": "job_queue_latency", "legendFormat": "{{quantile}} {{pod}}" }
   ]
  },
  {
   "title": "endpoint workqueue",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "endpoint_adds", "legendFormat": "adds  {{pod}}" },
    { "expr": "endpoint_retries", "legendFormat": "retries  {{pod}}" },
    { "expr": "endpoint_depth", "legendFormat": "depth  {{pod}}" }
   ]
  },
  {
   "title": "endpoint work duration",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 30 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    { "expr": "endpoint_work_duration", "legendFormat": " {{quantile}} {{pod}}" }
   ]
  },
  {
   "title": "endpoint queue latency",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 30 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    { "expr": "endpoint_queue_latency", "legendFormat": "{{quantile}} {{pod}}" }
   ]
  },
  { "title": "fixed replica controllers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "daemonset workqueue",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "daemonset_adds", "legendFormat": "adds {{pod}}" },
    { "expr": "daemonset_retries", "legendFormat": "retries  {{pod}}" },
    { "expr": "daemonset_depth", "legendFormat": "depth  {{pod}}" }
   ]
  },
  {
   "title": "daemonset work duration",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 35 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    { "expr": "daemonset_work_duration", "legendFormat": "{{quantile}} {{pod}}" }
   ]
  },
  {
   "title": "daemonset queue latency",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 35 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    { "expr": "daemonset_queue_latency", "legendFormat": "{{quantile}} {{pod}}" }
   ]
  },
  {
   "title": "replicationmanager workqueue",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "replicationmanager_adds", "legendFormat": "adds  {{pod}}" },
    { "expr": "replicationmanager_retries", "legendFormat": "retries  {{pod}}" },
    { "expr": "replicationmanager_depth", "legendFormat": "depth  {{pod}}" }
   ]
  },
  {
   "title": "replicationmanager work duration",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 39 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "replicationmanager_work_duration",
     "legendFormat": " {{quantile}} {{pod}}"
    }
   ]
  },
  {
   "title": "replicationmanager queue latency",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 39 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "replicationmanager_queue_latency",
     "legendFormat": "{{quantile}} {{pod}}"
    }
   ]
  },
  {
   "title": "replicaset workqueue",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "replicaset_adds", "legendFormat": "adds  {{pod}}" },
    { "expr": "replicaset_retries", "legendFormat": "retries  {{pod}}" },
    { "expr": "replicaset_depth", "legendFormat": "depth  {{pod}}" }
   ]
  },
  {
   "title": "replicaset work duration",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 43 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    { "expr": "replicaset_work_duration", "legendFormat": " {{quantile}} {{pod}}" }
   ]
  },
  {
   "title": "replicaset queue latency",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 43 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    { "expr": "replicaset_queue_latency", "legendFormat": "{{quantile}} {{pod}}" }
   ]
  },
  {
   "title": "statefulset workqueue",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "statefulset_adds", "legendFormat": "adds  {{pod}}" },
    { "expr": "statefulset_retries", "legendFormat": "retries  {{pod}}" },
    { "expr": "statefulset_depth", "legendFormat": "depth  {{pod}}" }
   ]
  },
  {
   "title": "statefulset work duration",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 47 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    { "expr": "statefulset_work_duration", "legendFormat": " {{quantile}} {{pod}}" }
   ]
  },
  {
   "title": "statefulset queue latency",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 47 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    { "expr": "statefulset_queue_latency", "legendFormat": "{{quantile}} {{pod}}" }
   ]
  },
  {
   "title": "other controller stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "claims workqueue",
     "type": "graph",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "claims_adds", "legendFormat": "adds  {{pod}}" },
      { "expr": "claims_retries", "legendFormat": "retries  {{pod}}" },
      { "expr": "claims_depth", "legendFormat": "depth  {{pod}}" }
     ]
    },
    {
     "title": "claims work duration",
     "type": "graph",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 9 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      { "expr": "claims_work_duration", "legendFormat": " {{quantile}} {{pod}}" }
     ]
    },
    {
     "title": "claims queue latency",
     "type": "graph",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 9 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      { "expr": "claims_queue_latency", "legendFormat": "{{quantile}} {{pod}}" }
     ]
    },
    {
     "title": "volumes workqueue",
     "type": "graph",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "volumes_adds", "legendFormat": "adds  {{pod}}" },
      { "expr": "volumes_retries", "legendFormat": "retries  {{pod}}" },
      { "expr": "volumes_depth", "legendFormat": "depth  {{pod}}" }
     ]
    },
    {
     "title": "volumes work duration",
     "type": "graph",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 13 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      { "expr": "volumes_work_duration", "legendFormat": " {{quantile}} {{pod}}" }
     ]
    },
    {
     "title": "volumes queue latency",
     "type": "graph",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 13 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      { "expr": "volumes_queue_latency", "legendFormat": "{{quantile}} {{pod}}" }
     ]
    }
   ]
  },
  { "title": "apiserver overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "api requests inflight histogram",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "apiserver_current_inflight_requests",
     "legendFormat": "{{requestKind}}@{{instance}}"
    }
   ]
  }
 ]
}