#!/bin/bash

# map PVS to storage paths
printf "%-40s\t%-40s\t%s\n" "PATH" "PV" "CLAIM"
PVS=$(oc get pv -o jsonpath='{.items[*].metadata.name}' | tr ' ' "\n")
declare -A PATH_TO_PV_MAP
while read pv <&3; do
  path=$(oc get pv ${pv} -o jsonpath='{.spec..path}')
  claim=$(oc get pv ${pv} -o jsonpath='{.spec.claimRef.name}')

  printf "%-40s\t%-40s\t%s\n" "${path}" "${pv}" "${claim}"
done 3<<<"${PVS}"

