{
 "title": "Capacity / Capacity Management",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Cluster Memory Utilisation",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(container_memory_usage_bytes{pod_name!=\"\"}) / sum(kube_node_status_allocatable_memory_bytes))",
     "legendFormat": "Cluster Memory Utilization"
    }
   ]
  },
  {
   "title": "Node Memory Utilisation",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "format": "percentunit",
   "valueName": "avg",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "1- sum(node_memory_MemFree + node_memory_Cached + node_memory_Buffers) / sum(node_memory_MemTotal)"
    }
   ]
  },
  {
   "title": "Total CPU Utilisation",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "format": "percentunit",
   "valueName": "avg",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "1- avg(rate(node_cpu{mode=\"idle\"}[10m]))"
    }
   ]
  },
  {
   "title": "Total Pod Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 6 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{pod_name!=\"\"})",
     "legendFormat": "Total Pod Usage Memory"
    }
   ]
  },
  {
   "title": "Total Allocable Memory",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 6 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_memory_bytes)",
     "legendFormat": "Total Pod Usage Memory"
    }
   ]
  },
  {
   "title": "Total Node Memory (Active)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 6 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    { "expr": "sum(node_memory_MemTotal)", "legendFormat": "Total Pod Usage Memory" }
   ]
  },
  {
   "title": "Max memory usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "topk (5, (sum (node_memory_Inactive + node_memory_Active + node_memory_Dirty + node_memory_Unevictable) by (instance)))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Max CPU usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "topk (5, (sum (rate(node_cpu{mode!=\"idle\"}[10m])) by (instance)))",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}