{
 "title": "Router",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Top 10 Connection Rates",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Connections/second" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(rate(haproxy_backend_sessions_total{backend!~\"be_(no_)?sni\"}[10m])) without (instance))",
     "legendFormat": "{{backend}}"
    }
   ]
  },
  {
   "title": "Top 10 Error Response Rates",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(rate(haproxy_backend_http_responses_total{code!=\"2xx\"}[5m])) by (app, code))",
     "legendFormat": "{{app}} - {{code}}"
    }
   ]
  },
  {
   "title": "Current Sessions By Router",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(haproxy_backend_current_sessions) by (instance)"
    }
   ]
  },
  {
   "title": "Network Activity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{region=\"infra\",device=~\"eth.\"}[5m])",
     "legendFormat": "{{instance}} - {{device}}"
    }
   ]
  },
  {
   "title": "Free Memory on Infra",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemFree{region=\"infra\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Load for Infra",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{region=\"infra\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}