{
 "title": "K8s / Custom / DevOps",
 "time": { "from": "now/M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 5, "x": 0, "y": 0 }, "content": "# Average Lead Time" },
  { "type": "text", "gridPos": { "h": 2, "w": 5, "x": 5, "y": 0 }, "content": "# Deployment Frequency" },
  { "type": "text", "gridPos": { "h": 2, "w": 5, "x": 10, "y": 0 }, "content": "# Mean Time to Restore" },
  { "type": "text", "gridPos": { "h": 2, "w": 5, "x": 15, "y": 0 }, "content": "# Change Failure Rate" },
  {
   "title": "This Month",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {}
   ]
  },
  {
   "title": "From Last Month",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 2, "y": 2 },
   "format": "percentunit",
   "valueName": "delta",
   "targets": [
    { "expr": "0" }
   ]
  },
  {
   "title": "Last $interval",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 5, "y": 2 },
   "format": "none",
   "valueName": "delta",
   "targets": [
    {
     "expr": "openshift_apps_deploymentconfigs_complete_rollouts_total{phase=\"available\"}[$interval]"
    }
   ]
  },
  {
   "title": "Change % in Last $interval",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 2 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(delta(openshift_apps_deploymentconfigs_complete_rollouts_total{phase=\"available\"}[$interval]))-sum(delta(openshift_apps_deploymentconfigs_complete_rollouts_total{phase=\"available\"}[$interval] offset $interval)))/sum(delta(openshift_apps_deploymentconfigs_complete_rollouts_total{phase=\"available\"}[$interval] offset $interval))"
    }
   ]
  },
  {
   "title": "This Month",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {}
   ]
  },
  {
   "title": "From Last Month",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 2 },
   "format": "percentunit",
   "valueName": "delta",
   "targets": [
    { "expr": "0" }
   ]
  },
  {
   "title": "This Month",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 15, "y": 2 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {}
   ]
  },
  {
   "title": "From Last Month",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 2 },
   "format": "percent",
   "valueName": "delta",
   "targets": [
    {}
   ]
  }
 ]
}