{
 "title": "Traffic",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Top 5 Network Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "topk(5, sum(rate(container_network_receive_bytes_total{pod_name!=\"\"}[5m])) by (pod_name))",
     "legendFormat": "RX: {{pod_name}} "
    },
    {
     "expr": "topk(5, sum(rate(container_network_transmit_bytes_total{pod_name!=\"\"}[5m])) by (pod_name))",
     "legendFormat": "TX: {{pod_name}}"
    }
   ]
  },
  {
   "title": "Pod Traffic (Receive)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{pod_name!=\"\"}[5m])) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Pod Traffic (Sent)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{pod_name!=\"\"}[5m])) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  }
 ]
}