{
 "title": "Capacity Management - 3.11",
 "tags": [ "RedHat COP" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "nodegroup",
    "label": "Node Group",
    "query": "label_values(kube_node_labels,label_nodegroup)"
   }
  ]
 },
 "panels": [
  {
   "title": "$nodegroup Node Group Memory Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Quota / Allocatable in Node Group: $nodegroup",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum (openshift_clusterresourcequota_labels{label_nodegroup=\"$nodegroup\"} * on (name) group_left () openshift_clusterresourcequota_usage{resource=\"requests.memory\",type=\"hard\"}) by (label_nodegroup))/(sum (kube_node_labels{label_nodegroup=\"$nodegroup\"} * on (node) group_left () kube_node_status_allocatable_memory_bytes) by (label_nodegroup))"
    }
   ]
  },
  {
   "title": "Pod requests / Allocatable in Node Group: $nodegroup",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum (kube_node_labels{label_nodegroup=\"$nodegroup\"} * on (node) group_left () sum (kube_pod_container_resource_requests_memory_bytes) by (node)) by (label_nodegroup))/(sum (kube_node_labels{label_nodegroup=\"$nodegroup\"} * on (node) group_left () kube_node_status_allocatable_memory_bytes) by (label_nodegroup))"
    }
   ]
  },
  {
   "title": "Current Memory Usage / Allocatable in Node Group: $nodegroup",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_labels{label_nodegroup=\"$nodegroup\"} * on (node) group_left () sum(kube_pod_info * on (pod) group_left() label_replace(sum(container_memory_usage_bytes{container_name=~\".+\", container_name!=\"POD\"}) by (pod_name),\"pod\",\"$1\",\"pod_name\", \"(.+)\")) by (node)) by (label_nodegroup)/(sum (kube_node_labels{label_nodegroup=\"$nodegroup\"} * on (node) group_left () kube_node_status_allocatable_memory_bytes) by (label_nodegroup))"
    }
   ]
  },
  {
   "title": "Sum of Quotas",
   "type": "singlestat",
   "description": "What has been promised",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum (openshift_clusterresourcequota_labels{label_nodegroup=\"$nodegroup\"} * on (name) group_left () openshift_clusterresourcequota_usage{resource=\"requests.memory\",type=\"hard\"}) by (label_nodegroup))"
    }
   ]
  },
  {
   "title": "Sum of Pod Requests",
   "type": "singlestat",
   "description": "What developers estimate they will need",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum (kube_node_labels{label_nodegroup=\"$nodegroup\"} * on (node) group_left () sum (kube_pod_container_resource_requests_memory_bytes) by (node)) by (label_nodegroup))"
    }
   ]
  },
  {
   "title": "Current Memory Utilization",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_labels{label_nodegroup=\"$nodegroup\"} * on (node) group_left () sum(kube_pod_info * on (pod) group_left() label_replace(sum(container_memory_usage_bytes{container_name=~\".+\", container_name!=\"POD\"}) by (pod_name),\"pod\",\"$1\",\"pod_name\", \"(.+)\")) by (node)) by (label_nodegroup)"
    }
   ]
  },
  {
   "title": "$nodegroup Node Group CPU Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }
  },
  {
   "title": "Quota/ Allocatable in Node Group: $nodegroup",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 9 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum (openshift_clusterresourcequota_labels{label_nodegroup=\"$nodegroup\"} * on (name) group_left () openshift_clusterresourcequota_usage{resource=\"requests.cpu\",type=\"hard\"}) by (label_nodegroup))/(sum (kube_node_labels{label_nodegroup=\"$nodegroup\"} * on (node) group_left () kube_node_status_allocatable_cpu_cores) by (label_nodegroup))"
    }
   ]
  },
  {
   "title": "Pod requests / Allocatable in Node Group: $nodegroup",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 9 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum (kube_node_labels{label_nodegroup=\"$nodegroup\"} * on (node) group_left () sum (kube_pod_container_resource_requests_cpu_cores) by (node)) by (label_nodegroup))/(sum (kube_node_labels{label_nodegroup=\"$nodegroup\"} * on (node) group_left () kube_node_status_allocatable_cpu_cores) by (label_nodegroup))"
    }
   ]
  },
  {
   "title": "Current CPU Usage in Node Group: $nodegroup",
   "type": "singlestat",
   "description": "OS and Container CPU usage",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 9 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_labels{label_nodegroup=\"$nodegroup\"} * on (node) group_left () sum(kube_pod_info * on (pod) group_left() label_replace(sum(rate (container_cpu_usage_seconds_total{container_name=~\".+\", container_name!=\"POD\"} [1m])) by (pod_name),\"pod\",\"$1\",\"pod_name\", \"(.+)\")) by (node)) by (label_nodegroup) / (sum (kube_node_labels{label_nodegroup=\"$nodegroup\"} * on (node) group_left () kube_node_status_allocatable_cpu_cores) by (label_nodegroup)) / (sum (kube_node_labels{label_nodegroup=\"$nodegroup\"} * on (node) group_left () kube_node_status_allocatable_cpu_cores) by (label_nodegroup))"
    }
   ]
  },
  {
   "title": "Sum of Quotas",
   "type": "singlestat",
   "description": "What has been promised",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum (openshift_clusterresourcequota_labels{label_nodegroup=\"$nodegroup\"} * on (name) group_left () openshift_clusterresourcequota_usage{resource=\"requests.cpu\",type=\"hard\"}) by (label_nodegroup))"
    }
   ]
  },
  {
   "title": "Sum of Pod Requests",
   "type": "singlestat",
   "description": "What developers estimate they will need",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum (kube_node_labels{label_nodegroup=\"$nodegroup\"} * on (node) group_left () sum (kube_pod_container_resource_requests_cpu_cores) by (node)) by (label_nodegroup))"
    }
   ]
  },
  {
   "title": "Current CPU Utilization",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_labels{label_nodegroup=\"$nodegroup\"} * on (node) group_left () sum(kube_pod_info * on (pod) group_left() label_replace(sum(rate (container_cpu_usage_seconds_total{container_name=~\".+\", container_name!=\"POD\"} [1m])) by (pod_name),\"pod\",\"$1\",\"pod_name\", \"(.+)\")) by (node)) by (label_nodegroup) / (sum (kube_node_labels{label_nodegroup=\"$nodegroup\"} * on (node) group_left () kube_node_status_allocatable_cpu_cores) by (label_nodegroup))"
    }
   ]
  }
 ]
}