{
 "title": "Capacity Planning (ResourceQuota)",
 "tags": [ "BMO" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "nodeselector",
    "label": "Project Node Selector",
    "query": "label_values(kube_namespace_annotations,annotation_openshift_io_node_selector)"
   },
   { "name": "noderole", "label": "Node Role", "query": "kube_node_labels" }
  ]
 },
 "panels": [
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory allocation ratio",
   "type": "singlestat",
   "description": "For Zone Main only\n\nNode Label>> label_node_role_kubernetes_io_compute=\"true\"\n\nProject Annotation>> annotation_openshift_io_node_selector=\"node-role.kubernetes.io/compute=true\"",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(\n  max(kube_namespace_annotations{annotation_openshift_io_node_selector=\"$nodeselector\"}) by (namespace)\n  *\n  max(kube_resourcequota{resource=~\".*memory\",type=\"hard\"}) by (namespace)\n)\n/\nsum(\n  max(kube_node_labels{$noderole}) by (node)\n  *\n  sum  by (node) (kube_node_status_allocatable_memory_bytes)\n)"
    }
   ]
  },
  {
   "title": "Memory request ratio (Request/Allocable)",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(\n  max(kube_namespace_annotations{annotation_openshift_io_node_selector=\"$nodeselector\"}) by (namespace)\n  *\n  max(kube_resourcequota{resource=~\".*memory\",type=\"used\"}) by (namespace)\n)\n/\nsum(\n  max(kube_node_labels{$noderole}) by (node)\n  *\n  sum  by (node) (kube_node_status_allocatable_memory_bytes)\n)"
    }
   ]
  },
  {
   "title": "Actual Memory Usage ratio (Usage/Allocable)",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(\n  sum(kube_pod_info) by (node,pod)\n   * on(node) group_left()\n  max(kube_node_labels{$noderole}) by (node)\n   *\n  on(pod)\n  group_right(node)\n  label_replace(\n    sum by (pod_name) (\n      container_memory_usage_bytes{namespace!~\"default|openshift-.*|kube-.*|cert-manager\", namespace!=\"\", image!=''}\n    ), \"pod\", \"$1\", \"pod_name\", \"(.+)\"\n  )\n)\n/\nsum(\n  max(kube_node_labels{$noderole}) by (node)\n  *\n  sum  by (node) (kube_node_status_allocatable_memory_bytes)\n)"
    }
   ]
  },
  {
   "title": "Total Memory Allocated",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 8 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(\n  max(kube_namespace_annotations{annotation_openshift_io_node_selector=\"$nodeselector\"}) by (namespace)\n  *\n  max(kube_resourcequota{resource=~\".*memory\",type=\"hard\"}) by (namespace)\n)"
    }
   ]
  },
  {
   "title": "Total Memory Used (Actual)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 8 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(\n  max(kube_namespace_annotations{annotation_openshift_io_node_selector=\"$nodeselector\"}) by (namespace)\n  *\n  max(kube_resourcequota{resource=~\".*memory\",type=\"used\"}) by (namespace)\n)"
    }
   ]
  },
  {
   "title": "Total Allocable Memory",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 8 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(\n  max(kube_node_labels{$noderole}) by (node)\n  *\n  sum  by (node) (kube_node_status_allocatable_memory_bytes)\n)"
    }
   ]
  },
  {
   "title": "Top 5 memory usage ratio (Request/Allocated)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "topk( 5, sum(kube_resourcequota{resource=~\".*memory\",type=\"used\"}) by (namespace) / ignoring(resource, type) sum(kube_resourcequota{resource=~\".*memory\",type=\"hard\"}) by (namespace))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Memory Quota/Usage per Project",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum(kube_resourcequota{resource=~\".*memory\",type=\"used\"}) by (namespace)"
    },
    {
     "expr": "sum(kube_resourcequota{resource=~\".*memory\",type=\"hard\"}) by (namespace)"
    },
    {
     "expr": "100 * sum(kube_resourcequota{resource=~\".*memory\",type=\"used\"}) by (namespace) / ignoring(resource, type) sum(kube_resourcequota{resource=~\".*memory\",type=\"hard\"}) by (namespace)"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "CPU allocation ratio",
   "type": "singlestat",
   "description": "For Zone Main only\n\nNode Label>> label_node_role_kubernetes_io_compute=\"true\"\n\nProject Annotation>> annotation_openshift_io_node_selector=\"node-role.kubernetes.io/compute=true\"",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(\n  max(kube_namespace_annotations{annotation_openshift_io_node_selector=\"$nodeselector\"}) by (namespace)\n  *\n  max(kube_resourcequota{resource=~\".*cpu\",type=\"hard\"}) by (namespace)\n)\n/\nsum(\n  max(kube_node_labels{$noderole}) by (node)\n  *\n  sum  by (node) (kube_node_status_allocatable_cpu_cores)\n)"
    }
   ]
  },
  {
   "title": "CPU request ratio (Request/Allocable)",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(\n  max(kube_namespace_annotations{annotation_openshift_io_node_selector=\"$nodeselector\"}) by (namespace)\n  *\n  max(kube_resourcequota{resource=~\".*cpu\",type=\"used\"}) by (namespace)\n)\n/\nsum(\n  max(kube_node_labels{$noderole}) by (node)\n  *\n  sum  by (node) (kube_node_status_allocatable_cpu_cores)\n)"
    }
   ]
  },
  {
   "title": "Actual Node CPU Utilisation ($noderole Zone)",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg (sum (rate(node_cpu{mode!=\"idle\"}[10m])) by (instance,pod)\n * on (pod) group_left()\n\nmax(\n  sum(kube_pod_info{pod=~\"node-exporter.*\"}) by (node,pod)\n   * on(node) group_left()\n  max(kube_node_labels{$noderole}) by (node)\n) by (pod))"
    }
   ]
  },
  {
   "title": "Total CPU Allocated",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 23 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(\n  max(kube_namespace_annotations{annotation_openshift_io_node_selector=\"$nodeselector\"}) by (namespace)\n  *\n  max(kube_resourcequota{resource=~\".*cpu\",type=\"hard\"}) by (namespace)\n)"
    }
   ]
  },
  {
   "title": "Total Actual CPU Used",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 23 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(\n  max(kube_namespace_annotations{annotation_openshift_io_node_selector=\"$nodeselector\"}) by (namespace)\n  *\n  max(kube_resourcequota{resource=~\".*cpu\",type=\"used\"}) by (namespace)\n)"
    }
   ]
  },
  {
   "title": "Total Allocable CPU",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 23 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(\n  max(kube_node_labels{$noderole}) by (node)\n  *\n  sum  by (node) (kube_node_status_allocatable_cpu_cores)\n)"
    }
   ]
  },
  {
   "title": "Top 5 CPU usage ratio (Request/Allocated)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "topk( 5, sum(kube_resourcequota{resource=~\".*cpu\",type=\"used\"}) by (namespace) / ignoring(resource, type) sum(kube_resourcequota{resource=~\".*cpu\",type=\"hard\"}) by (namespace))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "CPU Quota/Usage per Project",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "sum(kube_resourcequota{resource=~\".*cpu\",type=\"used\"}) by (namespace)"
    },
    {
     "expr": "sum(kube_resourcequota{resource=~\".*cpu\",type=\"hard\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    },
    {
     "expr": "100 * sum(kube_resourcequota{resource=~\".*cpu\",type=\"used\"}) by (namespace) / ignoring(resource, type) sum(kube_resourcequota{resource=~\".*cpu\",type=\"hard\"}) by (namespace)"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Storage utilisation ratio (glusterfs)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 31 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_resourcequota{resource=\"glusterfs.storageclass.storage.k8s.io/requests.storage\",type=\"used\"}) / sum(kube_resourcequota{resource=\"glusterfs.storageclass.storage.k8s.io/requests.storage\",type=\"hard\"})"
    }
   ]
  }
 ]
}