{
 "title": "Capacity Planning (ClusterResourceQuota)",
 "tags": [ "BMO" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "zone",
    "label": "Zone",
    "query": "label_values(kube_node_labels,label_zone)"
   }
  ]
 },
 "panels": [
  { "title": "Cluster Memory Quota", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster Memory Allocation Ratio- Quota/Allocable ($zone Zone)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(\n  max(openshift_clusterresourcequota_labels{label_zone=\"$zone\"}) by (label_zone, name)\n  * on (name)\n  group_right(label_zone)\n  sum (openshift_clusterresourcequota{resource=~\".*memory\",type=\"hard\"}) by (name)\n)\n\n/\nsum(\n  max(kube_node_labels{label_zone=\"$zone\"}) by (node)\n  *\n  sum  by (node) (kube_node_status_allocatable_memory_bytes)\n)"
    }
   ]
  },
  {
   "title": "Cluster Memory Request Ratio- Request/Allocable ($zone Zone)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(\n  max(openshift_clusterresourcequota_labels{label_zone=\"$zone\"}) by (label_zone, name)\n  * on (name)\n  group_right(label_zone)\n  sum (openshift_clusterresourcequota{resource=~\".*memory\",type=\"used\"}) by (name)\n)\n/\nsum(\n  max(kube_node_labels{label_zone=\"$zone\"}) by (node)\n  *\n  sum  by (node) (kube_node_status_allocatable_memory_bytes)\n)"
    }
   ]
  },
  {
   "title": "Cluster Memory Actual Usage Ratio- Usage/Allocable ($zone Zone)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(\n  sum(kube_pod_info) by (node,pod)\n   * on(node) group_left()\n  max(kube_node_labels{label_zone=\"$zone\"}) by (node)\n   *\n  on(pod)\n  group_right(node)\n  label_replace(\n    sum by (pod_name) (\n      container_memory_usage_bytes{namespace!~\"default|openshift-.*|kube-.*|cert-manager\", namespace!=\"\",image!=''}\n    ), \"pod\", \"$1\", \"pod_name\", \"(.+)\"\n  )\n)\n/\nsum(\n  max(kube_node_labels{label_zone=\"$zone\"}) by (node)\n  *\n  sum  by (node) (kube_node_status_allocatable_memory_bytes)\n)"
    }
   ]
  },
  {
   "title": "Allocated Memory",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(\n  max(openshift_clusterresourcequota_labels{label_zone=\"$zone\"}) by (label_zone, name)\n  * on (name)\n  group_right(label_zone)\n  sum (openshift_clusterresourcequota{resource=~\".*memory\",type=\"hard\"}) by (name)\n)"
    }
   ]
  },
  {
   "title": "Requested Memory",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(\n  max(openshift_clusterresourcequota_labels{label_zone=\"$zone\"}) by (label_zone, name)\n  * on (name)\n  group_right(label_zone)\n  sum (openshift_clusterresourcequota{resource=~\".*memory\",type=\"used\"}) by (name)\n)"
    }
   ]
  },
  {
   "title": "Total allocable memory ($zone Zone)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(\n  max(kube_node_labels{label_zone=\"$zone\"}) by (node)\n  *\n  sum  by (node) (kube_node_status_allocatable_memory_bytes)\n)"
    }
   ]
  },
  { "title": "Cluster CPU Quota", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Cluster CPU Allocation Ratio- Quota/Allocable ($zone Zone)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 9 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(\n  max(openshift_clusterresourcequota_labels{label_zone=\"$zone\"}) by (label_zone, name)\n  * on (name)\n  group_right(label_zone)\n  sum (openshift_clusterresourcequota{resource=~\".*cpu\",type=\"hard\"}) by (name)\n)\n\n/\nsum(\n  max(kube_node_labels{label_zone=\"$zone\"}) by (node)\n  *\n  sum  by (node) (kube_node_status_allocatable_cpu_cores)\n)"
    }
   ]
  },
  {
   "title": "Cluster CPU Request Ratio- Request/Allocable ($zone Zone)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 9 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(\n  max(openshift_clusterresourcequota_labels{label_zone=\"$zone\"}) by (label_zone, name)\n  * on (name)\n  group_right(label_zone)\n  sum (openshift_clusterresourcequota{resource=~\".*cpu\",type=\"used\"}) by (name)\n)\n/\nsum(\n  max(kube_node_labels{label_zone=\"$zone\"}) by (node)\n  *\n  sum  by (node) (kube_node_status_allocatable_cpu_cores)\n)"
    }
   ]
  },
  {
   "title": "Actual Node CPU Utilisation ($zone Zone)",
   "type": "singlestat",
   "description": "OS and Container CPU usage",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 9 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg (sum (rate(node_cpu{mode!=\"idle\"}[10m])) by (instance,pod)\n * on (pod) group_left()\n\nmax(\n  sum(kube_pod_info{pod=~\"node-exporter.*\"}) by (node,pod)\n   * on(node) group_left()\n  max(kube_node_labels{label_zone=~\"$zone\"}) by (node)\n) by (pod))"
    }
   ]
  },
  {
   "title": "Allocated CPU",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(\n  max(openshift_clusterresourcequota_labels{label_zone=\"$zone\"}) by (label_zone, name)\n  * on (name)\n  group_right(label_zone)\n  sum (openshift_clusterresourcequota{resource=~\".*cpu\",type=\"hard\"}) by (name)\n)"
    }
   ]
  },
  {
   "title": "Requested CPU",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(\n  max(openshift_clusterresourcequota_labels{label_zone=\"$zone\"}) by (label_zone, name)\n  * on (name)\n  group_right(label_zone)\n  sum (openshift_clusterresourcequota{resource=~\".*cpu\",type=\"used\"}) by (name)\n)"
    }
   ]
  },
  {
   "title": "Total allocable CPU ($zone Zone)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(\n  max(kube_node_labels{label_zone=\"$zone\"}) by (node)\n  *\n  sum  by (node) (kube_node_status_allocatable_cpu_cores)\n)"
    }
   ]
  },
  { "title": "Cluster Storage Quota", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Storage Allocation Ratio",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 17 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(openshift_clusterresourcequota{resource=\"glusterfs.storageclass.storage.k8s.io/requests.storage\",type=\"used\"}) / sum(openshift_clusterresourcequota{resource=\"glusterfs.storageclass.storage.k8s.io/requests.storage\",type=\"hard\"})"
    }
   ]
  }
 ]
}