{
 "title": "Capacity Planning(Cluster Resource Quota)",
 "tags": [ "RedHat COP" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "nodegroup",
    "label": "Node Group",
    "query": "label_values(kube_node_labels,label_nodegroup)"
   }
  ]
 },
 "panels": [
  { "title": "Cluster Memory Quota", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Quota / Allocatable in Node Group: $nodegroup",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(\n  max(openshift_clusterresourcequota_labels{label_nodegroup=\"$nodegroup\"}) by (label_nodegroup, name)\n  * on (name)\n  group_right(label_nodegroup)\n  sum (openshift_clusterresourcequota{resource=~\".*memory\",type=\"hard\"}) by (name)\n)\n\n/\nsum(\n  max(kube_node_labels{label_nodegroup=\"$nodegroup\"}) by (node)\n  *\n  sum  by (node) (kube_node_status_allocatable_memory_bytes)\n)"
    }
   ]
  },
  {
   "title": "Pod requests / Allocatable in Node Group: $nodegroup",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(\n  max(openshift_clusterresourcequota_labels{label_nodegroup=\"$nodegroup\"}) by (label_nodegroup, name)\n  * on (name)\n  group_right(label_nodegroup)\n  sum (openshift_clusterresourcequota{resource=~\".*memory\",type=\"used\"}) by (name)\n)\n/\nsum(\n  max(kube_node_labels{label_nodegroup=\"$nodegroup\"}) by (node)\n  *\n  sum  by (node) (kube_node_status_allocatable_memory_bytes)\n)"
    }
   ]
  },
  {
   "title": "Current Pod Usage / Allocatable in Node Group: $nodegroup",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(\n  max(kube_pod_info{created_by_kind!=\"Build\",pod!~\".*-deploy\"}) by (node,pod)\n   * on(node) group_left()\n  max(kube_node_labels{label_nodegroup=\"$nodegroup\"}) by (node)\n   *\n  on(pod)\n  group_right(node)\n  label_replace(\n    sum by (pod_name) (\n      container_memory_usage_bytes{namespace!=\"\",image!=''}\n    ), \"pod\", \"$1\", \"pod_name\", \"(.+)\"\n  )\n)\n/\nsum(\n  max(kube_node_labels{label_nodegroup=\"$nodegroup\"}) by (node)\n  *\n  sum  by (node) (kube_node_status_allocatable_memory_bytes)\n)"
    }
   ]
  },
  {
   "title": "Sum of Quotas",
   "type": "singlestat",
   "description": "What has been promised",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(\n  max(openshift_clusterresourcequota_labels{label_nodegroup=\"$nodegroup\"}) by (label_nodegroup, name)\n  * on (name)\n  group_right(label_nodegroup)\n  sum (openshift_clusterresourcequota{resource=~\".*memory\",type=\"hard\"}) by (name)\n)"
    }
   ]
  },
  {
   "title": "Sum of Pod Requests",
   "type": "singlestat",
   "description": "What developers estimate they will need",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(\n  max(openshift_clusterresourcequota_labels{label_nodegroup=\"$nodegroup\"}) by (label_nodegroup, name)\n  * on (name)\n  group_right(label_nodegroup)\n  sum (openshift_clusterresourcequota{resource=~\".*memory\",type=\"used\"}) by (name)\n)"
    }
   ]
  },
  {
   "title": "Current memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(\n  max(kube_pod_info{created_by_kind!=\"Build\",pod!~\".*-deploy\"}) by (node,pod)\n   * on(node) group_left()\n  max(kube_node_labels{label_nodegroup=\"main\"}) by (node)\n   *\n  on(pod)\n  group_right(node)\n  label_replace(\n    sum by (pod_name) (\n      container_memory_usage_bytes{namespace!=\"\",image!=\"\"}\n    ), \"pod\", \"$1\", \"pod_name\", \"(.+)\"\n  )\n)"
    }
   ]
  },
  {
   "title": "Memory Ratio Report",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(\n  max(openshift_clusterresourcequota_labels{label_nodegroup=\"$nodegroup\"}) by (label_nodegroup, name)\n  * on (name)\n  group_right(label_nodegroup)\n  sum (openshift_clusterresourcequota{resource=~\".*memory\",type=\"hard\"}) by (name)\n)\n\n/\nsum(\n  max(kube_node_labels{label_nodegroup=\"$nodegroup\"}) by (node)\n  *\n  sum  by (node) (kube_node_status_allocatable_memory_bytes)\n)",
     "legendFormat": "Allocation Ratio"
    },
    {
     "expr": "sum(\n  max(openshift_clusterresourcequota_labels{label_nodegroup=\"$nodegroup\"}) by (label_nodegroup, name)\n  * on (name)\n  group_right(label_nodegroup)\n  sum (openshift_clusterresourcequota{resource=~\".*memory\",type=\"used\"}) by (name)\n)\n/\nsum(\n  max(kube_node_labels{label_nodegroup=\"$nodegroup\"}) by (node)\n  *\n  sum  by (node) (kube_node_status_allocatable_memory_bytes)\n)",
     "legendFormat": "Request Ratio"
    },
    {
     "expr": "sum(\n  max(kube_pod_info{created_by_kind!=\"Build\",pod!~\".*-deploy\"}) by (node,pod)\n   * on(node) group_left()\n  max(kube_node_labels{label_nodegroup=\"$nodegroup\"}) by (node)\n   *\n  on(pod)\n  group_right(node)\n  label_replace(\n    sum by (pod_name) (\n      container_memory_usage_bytes{namespace!~\"default|openshift-.*|kube-.*|cert-manager\", namespace!=\"\",image!=''}\n    ), \"pod\", \"$1\", \"pod_name\", \"(.+)\"\n  )\n)\n/\nsum(\n  max(kube_node_labels{label_nodegroup=\"$nodegroup\"}) by (node)\n  *\n  sum  by (node) (kube_node_status_allocatable_memory_bytes)\n)",
     "legendFormat": "Actual Usage Ratio"
    }
   ]
  },
  { "title": "Cluster CPU Quota", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Quota/ Allocatable in Node Group: $nodegroup",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 13 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(\n  max(openshift_clusterresourcequota_labels{label_nodegroup=\"$nodegroup\"}) by (label_nodegroup, name)\n  * on (name)\n  group_right(label_nodegroup)\n  sum (openshift_clusterresourcequota{resource=~\".*cpu\",type=\"hard\"}) by (name)\n)\n\n/\nsum(\n  max(kube_node_labels{label_nodegroup=\"$nodegroup\"}) by (node)\n  *\n  sum  by (node) (kube_node_status_allocatable_cpu_cores)\n)"
    }
   ]
  },
  {
   "title": "Pod requests / Allocatable in Node Group: $nodegroup",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 13 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(\n  max(openshift_clusterresourcequota_labels{label_nodegroup=\"$nodegroup\"}) by (label_nodegroup, name)\n  * on (name)\n  group_right(label_nodegroup)\n  sum (openshift_clusterresourcequota{resource=~\".*cpu\",type=\"used\"}) by (name)\n)\n/\nsum(\n  max(kube_node_labels{label_nodegroup=\"$nodegroup\"}) by (node)\n  *\n  sum  by (node) (kube_node_status_allocatable_cpu_cores)\n)"
    }
   ]
  },
  {
   "title": "Actual Node CPU Utilisation (Node+Pod)",
   "type": "singlestat",
   "description": "OS and Container CPU usage",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 13 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg (avg (rate(node_cpu{mode!=\"idle\"}[10m])) by (instance,pod)\n * on (pod) group_left()\n\nmax(\n  sum(kube_pod_info{pod=~\"node-exporter.*\"}) by (node,pod)\n   * on(node) group_left()\n  max(kube_node_labels{label_nodegroup=~\"$nodegroup\"}) by (node)\n) by (pod))"
    }
   ]
  },
  {
   "title": "Sum of Granted Quotas",
   "type": "singlestat",
   "description": "What has been promised",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(\n  max(openshift_clusterresourcequota_labels{label_nodegroup=\"$nodegroup\"}) by (label_nodegroup, name)\n  * on (name)\n  group_right(label_nodegroup)\n  sum (openshift_clusterresourcequota{resource=~\".*cpu\",type=\"hard\"}) by (name)\n)"
    }
   ]
  },
  {
   "title": "Sum of Pod Requests",
   "type": "singlestat",
   "description": "What developers estimate they will need",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(\n  max(openshift_clusterresourcequota_labels{label_nodegroup=\"$nodegroup\"}) by (label_nodegroup, name)\n  * on (name)\n  group_right(label_nodegroup)\n  sum (openshift_clusterresourcequota{resource=~\".*cpu\",type=\"used\"}) by (name)\n)"
    }
   ]
  },
  {
   "title": "Total allocable CPU ($nodegroup Node Group)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(\n  max(kube_node_labels{label_nodegroup=\"$nodegroup\"}) by (node)\n  *\n  sum  by (node) (kube_node_status_allocatable_cpu_cores)\n)"
    }
   ]
  },
  {
   "title": "CPU Ratio Report",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(\n  max(openshift_clusterresourcequota_labels{label_nodegroup=\"$nodegroup\"}) by (label_nodegroup, name)\n  * on (name)\n  group_right(label_nodegroup)\n  sum (openshift_clusterresourcequota{resource=~\".*cpu\",type=\"hard\"}) by (name)\n)\n\n/\nsum(\n  max(kube_node_labels{label_nodegroup=\"$nodegroup\"}) by (node)\n  *\n  sum  by (node) (kube_node_status_allocatable_cpu_cores)\n)",
     "legendFormat": "Allocation Ratio"
    },
    {
     "expr": "sum(\n  max(openshift_clusterresourcequota_labels{label_nodegroup=\"$nodegroup\"}) by (label_nodegroup, name)\n  * on (name)\n  group_right(label_nodegroup)\n  sum (openshift_clusterresourcequota{resource=~\".*cpu\",type=\"used\"}) by (name)\n)\n/\nsum(\n  max(kube_node_labels{label_nodegroup=\"$nodegroup\"}) by (node)\n  *\n  sum  by (node) (kube_node_status_allocatable_cpu_cores)\n)",
     "legendFormat": "Request Ratio"
    },
    {
     "expr": "avg (avg (rate(node_cpu{mode!=\"idle\"}[10m])) by (instance,pod)\n * on (pod) group_left()\n\nmax(\n  sum(kube_pod_info{pod=~\"node-exporter.*\"}) by (node,pod)\n   * on(node) group_left()\n  max(kube_node_labels{label_nodegroup=~\"$nodegroup\"}) by (node)\n) by (pod))",
     "legendFormat": "Actual Utilisation"
    }
   ]
  },
  { "title": "Cluster Storage Quota", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Storage Allocation Ratio",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 25 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(openshift_clusterresourcequota{resource=\"glusterfs.storageclass.storage.k8s.io/requests.storage\",type=\"used\"}) / sum(openshift_clusterresourcequota{resource=\"glusterfs.storageclass.storage.k8s.io/requests.storage\",type=\"hard\"})"
    }
   ]
  },
  {
   "title": "Total Storage Allocated",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 11, "x": 12, "y": 25 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(openshift_clusterresourcequota{resource=\"glusterfs.storageclass.storage.k8s.io/requests.storage\",type=\"hard\"})"
    }
   ]
  },
  {
   "title": "Total Storage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 30 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(heketi_device_size_bytes)/3"
    }
   ]
  },
  {
   "title": "Free Storage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 6, "y": 30 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(heketi_device_free_bytes)/3"
    }
   ]
  },
  {
   "title": "Used Storage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 11, "y": 30 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(heketi_device_used_bytes)/3"
    }
   ]
  },
  {
   "title": "PVC size",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 7, "x": 16, "y": 30 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_persistentvolumeclaim_resource_requests_storage_bytes)"
    }
   ]
  }
 ]
}