---
- name: OCP PV Migrate
  hosts: localhost
  module_defaults:
    group/k8s:
      host: "{{ k8s_host }}"
      validate_certs: "{{ k8s_validate_certs | default(true) }}"
  tasks:
    - block:
      - name: Get K8s access token
        k8s_auth:
          username: "{{ k8s_username }}"
          password: "{{ k8s_password }}"
        register: k8s_auth_results

      - name: Set k8s_api_key
        set_fact:
          k8s_api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
      when: (k8s_api_key is not defined) and ((k8s_username is defined) and (k8s_password is defined))


    - name: OCP PV Migrate | Loop namespaces to migrate PVS per namespace
      include_tasks: k8s_migrate_pvs_for_namespace.yml
      loop: "{{ k8s_migraiton_namespaces }}"
      loop_control:
        loop_var: k8s_namespace
    
