kind: NetworkPolicy
apiVersion: extensions/v1beta1
metadata:
  name: asb-etcd-ingress
spec:
  podSelector:
    matchLabels:
      app: etcd
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app: openshift-ansible-service-broker
      ports:
        - port: 2379
          protocol: TCP